### ISSUE TITLE
Bug Reporting and Enhancement Policy

### ISSUE THREAD

**Issue by aazaff** [paleobiodb/PBDB_changelog#1]
1. Do we want people to file bugs in the service-appropriate repository (e.g., navigator bugs in the navigator repository), or all bugs in this repository? 

2. Also, what about enhancement requests or questions as opposed to bug reporting?

**Comment by vjpsyverson** [comment]
All issues will be filed here. If an issue needs to be moved to one of the other repositories to make it easier to track, someone from the development team can close it here and open a new issue there.
