### ISSUE TITLE
Taxon names entered into the Search Dialog Box returning collections not taxon page

### ISSUE THREAD

**Issue by jmarcot** [paleobiodb/PBDB_changelog#10]
When I enter a taxon name into the text box in the upper right corner of the Classic interface, it is returning collections containing that taxon, rather than the typical "taxon page." The only way I have found to access the taxon page is to click on a collection, then click on the name of the taxon in the occurrences.

**Comment by jpjenk** [comment]
Unable to duplicate this. If the taxon name being searched appears in the name of a collection, the algorithm could return the matching collections before matching taxon.

Best way to avoid ambiguity is to use the "Search for a taxon" function from the main menu. This form is considerably more flexible and powerful.

**Comment by jmarcot** [comment]
I figured this one out. It appears that the search box is case sensitive. If you type "Dinosauria" it goes to the taxon page. If you type "dinosauria" it gives you a list of collections with occurrences of Dinosauria. Is this the appropriate behavior? I think it used to take uncapitalized taxon names to the appropriate taxon page.
