### ISSUE TITLE
Precambrian monkey?

### ISSUE THREAD

**Issue by HFoxii** [paleobiodb/PBDB_changelog#37]
_Simia_ Mikhailova and Jankauskas 1989 (acritarch) is not equal to _Simia_ Linnaeus 1758 (primate; now suppressed). Due to this error, primates and all parent taxa are listed as having Ediacaran origin.

Collections with _Simia_ Mikhailova and Jankauskas 1989:
* https://paleobiodb.org/classic/basicCollectionSearch?collection_no=221270
* https://paleobiodb.org/classic/basicCollectionSearch?collection_no=221354

**Comment by pnovack-gottshall** [comment]
This now looks to be resolved. I'm unable to close the issue, though.
