### ISSUE TITLE
FAQ Updates

### ISSUE THREAD

**Issue by aazaff** [paleobiodb/PBDB_changelog#4]
Update the FAQ page to reflect recent changes to the database
- [x] Update current funding and development team information.
- [x] Update the bug reporting and feature requests to link to this issues page.
- [x] Update the paleogeographic rotations information.

**Comment by vjpsyverson** [comment]
@aazaff can you send me what the new info on the paleogeographic rotations should say?

**Comment by aazaff** [comment]
Paleobiology Database collections now use an EarthByte paleocoordinate rotation model as the default. 

Wright et al. (2013) Towards community-driven paleogeographic reconstructions: integrating open-access paleogeographic and paleobiology data with plate tectonics. *Biogeosciences* 10:1529-1541

Other paleocoordinate models (e.g., Scotese) can still be requested when downloading data by choosing different download options.

**Comment by vjpsyverson** [comment]
@markuhen requests also: "Can we change the behavior of the Resource page so that when you click on a resource it spawns a new page vs. leaving PBDB to go to the resource location?"

**Comment by aazaff** [comment]
I think that Marks request should be filed as a separate issue.

**Comment by vjpsyverson** [comment]
Well, I'm fixing both in the next update so I don't think I'll bother. That was just a "note to self" sort of thing. I'll delete it if you like though?

**Comment by vjpsyverson** [comment]
Just to clarify: does that replace the entire FAQ text about paleocoordinates -- i.e. do we no longer use GPlates?

**Comment by aazaff** [comment]
GPlates is a GIS program that can take a variety of different rotation models, and is not itself a rotation model. It was a mistake for us to refer to the previous model as GPlates in the PBDB and Macrostrat documentation. Give me a second, and I will update my previous answer to be more thorough.

As for filing a new issue. It's not a big deal, but I'm just trying to keep things tidy. It's standard GitHub practice to file distinct issues separately for record keeping purposes, but we're not exactly a large professional outfit so it doesn't really matter.

**Comment by vjpsyverson** [comment]
Navigator, then, uses the GPlates visualization software with the EarthByte model?

**Comment by aazaff** [comment]
Actually, I'm not even sure that the current Navigator polygons are updated to match the current EarthByte model. @jczaplew was the primary developer of navigator, but since he's not directly involved with PBDB development anymore, I don't know who is responsible for keeping things updated.

**Comment by aazaff** [comment]
@jczaplew confirms that the current Navigator polygons are not updated.

**Comment by vjpsyverson** [comment]
Ugh, ok. Please correct the current text of the bit on paleogeographic coordinates in its entirety and send me a version that's accurate and complete, because I don't know how this works.

Current version on the live site: 

>     Collections in the Paleobiology Database are assigned present-day coordinates and geological ages. These two pieces of information are combined with paleogeographic rotation models to obtain reconstructed paleogeographic positions. We use two different plate rotation models. The first are the rotations provided to us by Christopher Scotese (http://www.scotese.com). These rotations have not changed for years and will not change in the future. The second source is GPlates. GPlates data are obtained by dynamic calls to web data services managed by the GPlates team (we have worked closely with Mike Gurnis and Mark Turner at CalTech). The GPlates rotations are used in the Navigator application and will continue to evolve as the GPlates model evolves. An appropriate current citation for GPlates rotations is: Wright, N. S. Zahirovic, R.D. Müller, M. Seton. 2013. Towards community-driven paleogeographic reconstructions: integrating open-access paleogeographic and paleobiology data with plate tectonics. Biogeosciences 10:1529-1541.

**Comment by vjpsyverson** [comment]
@markuhen, what's your ExCom chair official "@paleobiodb.org" e-mail?

**Comment by aazaff** [comment]
Okay I updated the paleogeography blurb. I'd like @cambro or @markuhen to look at it to make sure I haven't hit any political mines.

I'll file an issue in the Navigator repo about updating the polygons.

**Comment by aazaff** [comment]
Hi @markuhen, sorry my original comment wasn't clear. It's the third comment in this thread.

**Comment by aazaff** [comment]
@vjpsyverson, Mark approved the blurb, you can implement it at your leisure.

**Comment by vjpsyverson** [comment]
Done.
