### ISSUE TITLE
Navigator not opening

### ISSUE THREAD

**Issue by benwjohnson** [paleobiodb/PBDB_changelog#43]
Navigator appears to not open! It just gets stuck "Initializing"
<img width="467" alt="Screen Shot 2022-04-19 at 1 11 05 PM" src="https://user-images.githubusercontent.com/34067866/164068566-0f569058-0d03-4a8f-994c-ad0708ce2621.png">

**Comment by cambro** [comment]
This has been resolved. Sorry for the outage.

**Comment by benwjohnson** [comment]
Thank you!

------------------------------------------
Dr. Ben W Johnson
he/him/his
Assistant Professor
Iowa State University
Ancestral lands of the Baxoje (bah-kho-dzhe), or Ioway Nation
Department of Geological
  and Atmospheric Sciences
515-294-5823
http://www.benwjohnson.com
------------------------------------------
________________________________
