### ISSUE TITLE
Everything stopped working yesterday 4/18/2022. 

### ISSUE THREAD

**Issue by Paleofloodman** [paleobiodb/PBDB_changelog#44]
I thought maybe there was an update. It's been 24 hours now and still nothing works. 
![image](https://user-images.githubusercontent.com/104028281/164070944-27f0146a-9dc1-41c3-976e-c2f03891472b.png)
504 server for all species, all sites. Searches are just "Error something went wrong."

**Comment by cambro** [comment]
This has been resolved. Sorry for the outage.
