### ISSUE TITLE
wrong author reference for species Dipoides williamsi

### ISSUE THREAD

**Issue by rhulbert** [paleobiodb/PBDB_changelog#47]
The author and date for _Dipoides williamsi_ is correctly given as Stirton 1936, but the linked reference is for a different publication from the same year. The correct paper in which this species is named is Stirton RA 1936 A new beaver from the Pliocene of Arizona with notes on the species of _Dipoides_. Journal of Mammalogy 17(3):279-281

**Comment by pnovack-gottshall** [comment]
Thanks for catching the error, rhurlbert! I've corrected the reference.

**Comment by rhulbert** [comment]
The link to the Stirton paper on the top of the species page is fixed, but not the one in this line:
Belongs to Dipoides<https://paleobiodb.org/classic/basicTaxonInfo?taxon_no=41542> according to R. A. Stirton 1936<https://paleobiodb.org/classic/displayReference?reference_no=3231>

**Comment by pnovack-gottshall** [comment]
Thanks - I just corrected that one, too.  I don't appear to have the authority to close this issue, however, on GitHub
