### ISSUE TITLE
Map update needed

### ISSUE THREAD

**Issue by bethany-j-allen** [paleobiodb/PBDB_changelog#58]
The map on the 'Duplicate collection search form' currently shows the following error:
![Screenshot 2023-10-24 at 11 23 44](https://github.com/paleobiodb/bug_reports/assets/39991015/b9842fa2-cb60-4ddf-96b5-13c01a07d442)

**Comment by naheim** [comment]
This is a general problem, the same missing map tiles and warning message are showing up in Navigator.

**Comment by mmcclenn** [comment]
This has been fixed by switching over to Carto as our map tile provider.
