### ISSUE TITLE
Reidentified taxa assigned to unranked clades not displaying on collection page

### ISSUE THREAD

**Issue by PatHolroyd** [paleobiodb/PBDB_changelog#6]
Example:

https://paleobiodb.org/classic/basicCollectionSearch?collection_no=120887

This collection has two taxa, but only one displays.  Both are visible on the edit screen, but the taxon that has been reidentified and assigned to an unranked clade does not appear except in edit mode.

**Comment by jpjenk** [comment]
This issue appears to have been solved.
