### ISSUE TITLE
Cannot click on locality info from taxon pages

### ISSUE THREAD

**Issue by asrini2001** [paleobiodb/PBDB_changelog#66]
80% of the time, whenever I go to the page of a specific taxon and click on the locality information from there, the locality info redirects to a 403 error page. However, I am still able to access the locality info from the Visualize map page. Fixing this error would be greatly appreciated.

**Comment by pnovack-gottshall** [comment]
This is an ongoing issue. Until resolved ( @mmcclenn ), you can get around the error by clicking on "Show more details" on the Info page and then clicking on the individual collections on the "Age range and collections" tab.

**Comment by pnovack-gottshall** [comment]
This should now be fixed! Thanks for your patience!

**Comment by asrini2001** [comment]
It does, thanks! Noticed it a few days ago
