### ISSUE TITLE
Extinction/origination rate calculator

### ISSUE THREAD

**Issue by vjpsyverson** [paleobiodb/PBDB_changelog#8]
Requested with March deadline by education grant participants.

- [ ] Choose and describe algorithms (@vjpsyverson)

- [ ] Implement in API (@mmcclenn)

- [ ] Make available via downloader (@vjpsyverson)

- [ ] (optional) Add to Navigator (@vjpsyverson)

**Comment by jpjenk** [comment]
moved to paleobiodb-new
